# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidLldb31 < AndroidToolFormula
  desc "LLDB 3.1"
  url "https://dl.google.com/android/repository/lldb-3.1.4508709-darwin-x86_64.zip"
  version "3.1.4508709"
  sha1 "2b37aa55b81a7e5b8a369febf1ac0bad6c7c5d58"

  depends_on "pizzahutuk/android/android-sdk"
  depends_on "pizzahutuk/android/android-ndk"

  def install
    (prefix/"lldb"/"3.1").install Dir["*"]
    install_tools prefix/"lldb"/"3.1"

    pkg_xml = prefix/"lldb"/"3.1"/"package.xml"
    pkg_xml.delete if pkg_xml.exist?
    pkg_xml.write <<~EOS
      <ns4:repository xmlns:ns4="http://schemas.android.com/repository/android/common/01">
        <localPackage obsolete="false" path="lldb;3.1">
          <revision>
            <major>#{version.to_s.split(".")[0]}</major>
            <minor>#{version.to_s.split(".")[1]}</minor>
            <micro>#{version.to_s.split(".")[2]}</micro>
          </revision>
          <display-name>#{desc}</display-name>
        </localPackage>
      </ns4:repository>
    EOS

    link_sdk_dir "lldb"
  end

  test do
    system "true"
  end
end
