# This file is autogenerated by the generate-sdks.sh script

require "pathname"
require Pathname(__FILE__).realpath.dirname.join("../lib", "android-tool-formula") unless defined?(android_tool_formula)

class AndroidPlatformTools < AndroidToolFormula
  url "https://dl.google.com/android/repository/platform-tools_r27.0.1-darwin.zip"
  version "27.0.1"
  sha1 "d7b60f4022ee90e647af0c2ac605f2f99b4164c5"

  depends_on "pizzahutuk/android/android-sdk"

  def install
    (prefix/"platform-tools").install Dir["*"]
    install_tools prefix/"platform-tools"

    link_sdk_dir "platform-tools"
  end

  test do
    system "true"
  end
end
